steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t southamerica-east1-docker.pkg.dev/products-app-microservices/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_MS_DATABASE_URL=$$ORDERS_MS_DATABASE_URL .
    secretEnv: ['ORDERS_MS_DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/products-app-microservices/image-registry/orders-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/912735328601/secrets/ORDERS_MS_DATABASE_URL/versions/1
      env: 'ORDERS_MS_DATABASE_URL'
